# Generated by Django 5.1.7 on 2025-04-11 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='numero_factura_usuario',
        ),
    ]
