# Generated by Django 5.1.7 on 2025-04-11 23:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_remove_transaccion_numero_factura_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='numero_factura_usuario',
            field=models.PositiveIntegerField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
