# Generated by Django 5.1.7 on 2025-04-11 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0003_transaccion_numero_factura_usuario'),
    ]

    operations = [
    ]
