# Generated by Django 5.1.7 on 2025-04-11 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0004_auto_20250411_1836'),
        ('transacciones', '0004_auto_YYYYMMDD_HHMM'),
    ]

    operations = [
    ]
