# Generated by Django 5.1.7 on 2025-04-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0005_merge_0004_auto_20250411_1836_0004_auto_YYYYMMDD_HHMM'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='factuID',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
